# Generated by Django 6.0.6 on 2026-06-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='remarks',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('RENT', 'Rent'), ('DEPOSIT', 'Deposit')], default='RENT', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='PAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank'), ('CASH', 'Cash')], max_length=20),
        ),
    ]
