# Generated by Django 6.0.6 on 2026-07-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='occupation',
        ),
    ]
