# Generated by Django 6.0.6 on 2026-07-04 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'LANDLORD'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estates', to=settings.AUTH_USER_MODEL),
        ),
    ]
