# Generated by Django 6.0.6 on 2026-07-11 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_estate_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='estates.estate'),
        ),
    ]
