# Generated by Django 6.0.6 on 2026-07-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_alter_unit_estate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('estate', 'unit_number'), name='unique_unit_number_per_estate'),
        ),
    ]
