from django.urls import path
from .views import (
    dashboard_statistics,
    monthly_revenue_report,
    monthly_revenue_pdf,
    monthly_revenue_detail,
    monthly_revenue_detail_pdf,
    occupancy_report,
    occupancy_report_pdf,
    units_report,
    units_report_pdf,
    tenants_report,
    tenants_report_pdf,
    leases_report,
    leases_report_pdf,
    maintenance_summary,
    maintenance_summary_pdf,
    my_payments_pdf,
    payment_receipt_pdf,
)

urlpatterns = [
    path('dashboard/', dashboard_statistics, name='dashboard-statistics'),
    path('monthly-revenue/', monthly_revenue_report, name='monthly-revenue-report'),
    path('monthly-revenue/pdf/', monthly_revenue_pdf, name='monthly-revenue-pdf'),
    path('monthly-revenue/detail/', monthly_revenue_detail, name='monthly-revenue-detail'),
    path('monthly-revenue/detail/pdf/', monthly_revenue_detail_pdf, name='monthly-revenue-detail-pdf'),
    path('occupancy/', occupancy_report, name='occupancy-report'),
    path('occupancy/pdf/', occupancy_report_pdf, name='occupancy-report-pdf'),
    path('units/', units_report, name='units-report'),
    path('units/pdf/', units_report_pdf, name='units-report-pdf'),
    path('tenants/', tenants_report, name='tenants-report'),
    path('tenants/pdf/', tenants_report_pdf, name='tenants-report-pdf'),
    path('leases/', leases_report, name='leases-report'),
    path('leases/pdf/', leases_report_pdf, name='leases-report-pdf'),
    path('maintenance-summary/', maintenance_summary, name='maintenance-summary'),
    path('maintenance-summary/pdf/', maintenance_summary_pdf, name='maintenance-summary-pdf'),
    path('my-payments/pdf/', my_payments_pdf, name='my-payments-pdf'),
    path('payment-receipt/<int:payment_id>/pdf/', payment_receipt_pdf, name='payment-receipt-pdf'),
]