# Generated by Django 6.0.6 on 2026-07-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text="If True, the user is required to set a new password before they can use the system. Set automatically whenever an Admin or Manager creates an account or resets someone's password. Never enforced for ADMIN accounts, regardless of this value."),
        ),
    ]