# Generated by Django 6.0.6 on 2026-08-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_alter_lease_tenant_alter_lease_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank for an open-ended lease with no fixed end date.', null=True),
        ),
    ]